name: "Release new version"

on:
  push:
    tags:
      - "v*"

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: build artifacts
        run: ./build_and_pack.sh 2 ${{ github.ref }} && ./build_and_pack.sh 3 ${{ github.ref }}

